### PR TITLE
Add ReverseGeocoding Clojure sample function

### PR DESCRIPTION
**Pull request by lucj**
Signed-off-by: Luc Juggery <luc.juggery@gmail.com>

## Description

Added function which performs a reverse geocoding of GPS coordinates

## Motivation and Context

Was curious about how to add a Clojure function into OpenFaaS

## How Has This Been Tested?

Function has been created and invoked through the UI.
Once the function is created, it can be tested with the following query:
```
$ curl -d '7.116703 43.581915' http://localhost:8080/function/ReverseGeocoding
20 Avenue Reibaud, 06600 Antibes, France
```

## Types of changes

Added the ReverseGeocoding folder in sample-functions. This folder contains a Clojure project and the Dockerfile needed in order to build the image.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by scottyw** [comment]
Looks good to me!

The project file still contains mention of the default "Eclipse Public License". I wonder if it would be preferable to remove that?

**Comment by lucj** [comment]
Yes, I'll remove that one.

Le 11 sept. 2017 2:44 PM, "Scott Walker" <notifications@github.com> a
écrit :

**Comment by lucj** [comment]
Done (sorry why AFK).

**Comment by alexellis** [comment]
Hey @lucj I think this would be awesome to have in the showcase repository called faas-and-furious.

https://github.com/faas-and-furious

If you move this into your own repository I'll give you access to faas-and-furious and you can transfer the repo in.

**Comment by lucj** [comment]
Hi @alexellis, yes no problem.
Is this one fine https://github.com/lucj/faas-reverse-geocoding ?

**Comment by alexellis** [comment]
You're now a member, please go ahead and transfer the repo and close out the issue. Bonus points for a GIF too :+1:

**Comment by alexellis** [comment]
Please also PR to the community.md file with your repo in the last section along with the date and URL when ready.

**Comment by lucj** [comment]
Repo has been added. Animated Gif and PR on their way.

**Comment by lucj** [comment]
@alexellis just to be sure, you need me to close this PR and create a new one only with the changes of the community.md, correct ?

**Pull request closed without merging**
