### PR TITLE
add Azure deployment template

### PR DESCRIPTION
**Pull request by rcarmo**
## Description

This pull request adds a Resource Manager template for deploying FaaS on the Azure public cloud with automatic scaling of compute resources based on CPU load.

## Motivation and Context

This automates cloud infrastructure provisioning and paves the way to map function autoscaling to virtual machine autoscaling.

## How Has This Been Tested?

This is based on previous (well tested) work with minimal changes, and is usable from any Mac, Linux or Windows (with WSL) machine that has the Azure CLI installed.

It has no impact on existing code (and fetches all the Docker and Prometheus configs directly from the master branch)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rcarmo** [comment]
Sure!

**Comment by alexellis** [comment]
Can I find your email anywhere online?

**Comment by rcarmo** [comment]
yeah, just follow the link on my profile, check the footer of that page.

**Comment by alexellis** [comment]
This is quite a large changeset and I am not sure when I'll have time to test it out and review. Maybe we can submit it to a labs repo and iterate on it there?

https://github.com/get-faas/labs-azure-scaling-template

**Comment by rcarmo** [comment]
Well, it has no impact whatsoever on existing code in this repo, so it 
can be used standalone... There are some things that need addressing in 
terms of security and separation between admin and function invocation 
to make the whole thing work better, but this is just infra.

**Comment by rcarmo** [comment]
Moved to https://github.com/get-faas/labs-azure-scaling-template/pull/1

**Pull request closed without merging**
