### PR TITLE
Add try in pwd button.

### PR DESCRIPTION
**Pull request by marcosnils**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
This is cool.

Would be good to merge when 
- the stack name can match one given in the link (so that the test drive instructions match with the deploy_stack.sh function names)
- and the Safari scroll issue is fixed

**Comment by marcosnils** [comment]
Done @alexellis. /cc @alexellis

**Comment by alexellis** [comment]
Great! I'll try it out.

**Comment by developius** [comment]
After deployed to PWD, I can't access ports 9090 & 9093 - any reason for this? 8080 works fine for the UI.

**Comment by alexellis** [comment]
How did you deploy it to PWD - using the new button from @marcosnils or the TestDrive/script way ?

**Comment by alexellis** [comment]
@marcosnils only fails of deployed with the new button?

**Comment by marcosnils** [comment]
@alexellis if I either deploy it using the button or copying the docker-compose file and doing `docker stack deploy` the result is the same. Only 8080 is accessible. Not sure how 9090 and 9093 should be used though. The "Try in PWD"  does the same thing as if you deploy it manually with `docker stack deploy`

**Comment by marcosnils** [comment]
Another thing that I've noticed is that after deploying if I do `curl localhost:9090` or `curl localhost:9093` it doesn't work (which makes sense). I don't think it's a PWD issue.

**Comment by developius** [comment]
@alexellis I used the button. @marcosnils 9090 & 9093 are for Prometheus - they worked for me when I did a `docker stack deploy` on my own swarm.

**Comment by alexellis** [comment]
Opening 9090 in a browser worked for me yesterday with the TestDrive instructions. Also works on VMs.

**Pull request merged**
