### PR TITLE
Adding Faas-Tensorflow to the community page

### PR DESCRIPTION
**Pull request by jmkhael**
The example documents how to setup an image recognition FaaS based on Tensorflow.

### CODE REVIEW

**Comment by alexellis** [comment]
What's the merge conflict?

**Comment by jmkhael** [comment]
i should have done messed up somewhere... i'll close this one and redo

**Comment by alexellis** [comment]
I think your change is merged. Do you want to close this PR?

**Comment by alexellis** [comment]
I think your change is merged. Do you want to close this PR?

**Pull request closed without merging**
