### PR TITLE
added traefik.md

### PR DESCRIPTION
**Pull request by aafrey**
added traefik.md

## Description

Added instructions to use Traefik as a reverse proxy for FaaS

## Motivation and Context

It allows easy SSL setup and eventually should be able to support basic authentication.

N/A

## How Has This Been Tested?

I tested the included docker-compose.yml on a personel server and domain name. Requests through the frontend UI work as well as curl requests like the following `curl -X POST https://yourdomain.com/function/stack_nodeinfo`

N/A

N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for this. I have a couple of things to look at first, then I'll give this a test.

Are there any manual steps?

Thanks,

Alex

**Comment by aafrey** [comment]
@alexellis manual steps? there are no additional steps outside of running `docker deploy stack...`

**Comment by alexellis** [comment]
Hi @aafrey I would like to revisit this so will keep it on the project board and close for now.

**Comment by austinfrey** [comment]
@alexellis should we revisit this soon? I can look into this more this week

**Comment by austinfrey** [comment]
@alexellis i have Basic Authentication working for this now. So it could be another API Gateway option like Kong. This can also provide SSL support. I can write up a guide if it's of interest

**Pull request closed without merging**
