### PR TITLE
Added MakerShift to community.md

### PR DESCRIPTION
**Pull request by aafrey**
## Description

Added a new speaking event to community.md

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by aafrey** [comment]
I'm going to give the same sort of talk i gave last time, but i've tweaked the slides and had some really good feedback for improvements from the last one, so I'll be switching it up slightly. I'm also going to tweak my functions a bit

**Comment by alexellis** [comment]
OK great, how about [Makershift - Title of talk] ?

**Comment by aafrey** [comment]
Sure! I'll make the change after work tonight

**Comment by alexellis** [comment]
@aafrey ping for the title change, then I'll merge.

**Comment by aafrey** [comment]
@alexellis updated and squished :)

**Comment by alexellis** [comment]
Thanks!

**Pull request merged**
